language: go

go:
    - tip

before_install:
    - go get github.com/mattn/goveralls

install:
    - sudo add-apt-repository -y ppa:masterminds/glide && sudo apt-get update && sudo
      apt-get install glide
    - nvm install v6.7.0 && nvm use v6.7.0
    - make install

script:
    - make
    - "$HOME/gopath/bin/goveralls -service=travis-ci --ignore=server/bindata.go"


before_deploy:
    - zip -r kubryant appspec.yml conf/ docker-compose.* kubryant.in static/ vendor
    - mkdir -p deploy
    - mv kubryant.zip deploy/kubryant.zip

deploy:
    - provider: s3
      access_key_id: &1
          secure: oSb4mUIKxnjN1v7FGtyxU5vF+EbiR4cBrHn6LTBrTGKWzcI7x5HO8Amtbnkhklf8UOHJvhqm5zulpV3o3eR/QrsQicVY6spWtidu5Mz9LFMnx7eSNksuu9HDz/CtZb69xT4x+d2vSYxR6NnYTq81fJJ7nQtkXR7/0l3EaA+tWpWxNTS9hCZL5SN5ZhkLxGcI04F4e0XKo45/KPgf9++qSLtI52hRSH7vVGkF9tko55gNKGb0xO1X7CxS6SvsGz54A4u8rpWHwh09F9s7u1MnDCFAUC6gCVRUkBVjD6LQswLRa+p78mISzvjpxfENQ7FfWgiDojVSrd3WPB8BUHE1s3v1a3J9X0By53DXKjH1Zxg2sq01IciDklEY1zG4k8lDoyXRWiMfkkfK9p2Xx2iWEi7l7w0rPT2WttdWfclriut3bQKcNyrAaXt3NbpePVDr6wlJVzXwTU+MIPtm2jALRGYG5912EMSvPC4EK7n2ESzcWMP8rW6//IHnLkERvp4tMGLjjb2GjIq2+h4YPcHytTJ/38MqTUZ0SO1Ta/1eTQ3GzA6HQ3ghBKpr+qr+tSYHHUoGb0FtWH0DWGerB86eZq8w7vcy3DFP4IGnUBKkJjS43Sm2369jfy/meShoDjzHxC8wtRIzrPXm9yXKlVuFoCfTBn/GrQUFtywjam0HlCI=
      secret_access_key: &2
          secure: qKkReXiK4j68M9H2cHFpt1YaDnrJmzIz2GesMyLdBZ3voYpDaf7Ojmb9bauTigHSC1lpTn8ccms/rLmACYHNxO6zW/QhfTN9gAqOxXPxSEFn0IE1I3BaARnMLxJRds1l+gDftdbfN4ejC4KfnJGVPN0AOu27+jLmT2fi0TsneUuaxmSJsgC99JPaQ91hRGvg4nSpG3GIG98GaArUvtzhnRTKvNnpYBa53rRKS91HqKgxgs1v0PeZyyxnHx/4NbonO4YY97hCcbl0qmucWVld2CmYgPesx4Ra75GbubjTwd3yVctodU/3YA0PwyXhOusJtxMUw25t9dWBg19mf7+Regzw+zGV5NwF7N9ra+OGOPas6w6rBO53zXvqULPFMf/FCdBTeUSMuM9vsi8C/Stq2lIc4Qg23gZsMFSAxfatRVLhsxv7JsDqJBKve2+WqxNPqABc0aKF1VK/HAyPhtd1ZQhXMAunDDMg9WZ3EMVgNamgf7BdL7an5kiPpVTkX2Q6WKF2h5vjikyxqgbXFJeFSIqMdf6v6v/z9boV9n3wRHvU/mtKS3zrbdu8mo9GQEmrkGFucyMBr72cefBsLAG7GLfPsN4uTTEeg6rINc/ArS8jnmE5+IV2Jk4sjYJHZqsfJisaxejgz8GKrZf7uz+1utGlWuGnx+SGbMiZJi/G4Cg=
      bucket: kubryant
      local_dir: deploy
      skip_cleanup: true
      on: &3
          branch: master
    - provider: codedeploy
      access_key_id: *1
      secret_access_key: *2
      bucket: kubryant
      key: kubryant.zip
      bundle_type: zip
      application: kubryant
      deployment_group: production
      wait-until-deployed: true
      on: *3
