language: go

go:
    - tip

before_install:
    - go get github.com/mattn/goveralls

install:
    - sudo add-apt-repository -y ppa:masterminds/glide && sudo apt-get update && sudo
      apt-get install glide
    - nvm install v6.7.0 && nvm use v6.7.0
    - make install

script:
    - make
    - "$HOME/gopath/bin/goveralls -service=travis-ci --ignore=server/bindata.go"

deploy:
    provider: s3
    secure: GsnQkfcHnKf2DOALZqleqfqqb27uRZNRxfF3RFcIRfTY9nGZ5w5GML7c26l22xiQcVzDXMAG3hsGX0oUtXO9wFPaR5z9R9nav7TN5m61I3kc7LQGmzvSsCoESBsKqskxjeN1dlNA07IqP0h/Sa7XLMG2uuRpv9RuP0YZg7quuWH5LfxliGIC5HRPF/ypWEPqO510vrOu8PcjasZ6uzAcYa92WHp9+dNi+XJx6GS0S+vV2cCEx0JU6ZoaeNbafvuDhoONiaIlRZkCx5nI61bhyApikCZBpFEJAqjhPDqRb8QnshQ1mcT+/m67xCNvyDiQChXRKuEYaeLpmYsY1vKPRQTKh0TW76l70HyYIZO7hKguyATIQuzTBia49cMr97AP+JfSxe0se2ZFR0e02UE5psb13QAFVxayn0CVzwtL7FkH0velLX/e4JMvspLy1IBAhOzNg7pkWRcTXmGTEw/XLAHqB8GgDfP6O3tb1oJe1e2TWEDFTmNt/qp3vhLaIHCQ36ctOC2P7VLuImr17HoEGSd1AJ0SYPUZtGPZAswJb8ArvxWriR2ysBSLLcY5cE8snHvYcjbCaLDQJvKSayPUW7KquKCuqZw/XHo5KzNCz+YO69VeZjhIWXkKaJ838rZXwYaF36j3hQJ+0rLR2CZw/Gn4s8QA1QL/iF3gmiBnI8A=
    secure: Ctym4OE3/2ZwkyMVCro1IIt0gt98+8bOBs3yfi4SdP0nkLAoIVpt08EXHunZubOq8DvwcSnucx0iH35M7vXqzW3WJByqiqVF3HMgH3bpw+L56olQWr31rY/dWFY09hox3iE2z/VYYB1zYZxOCSyg9u1tukRgMqBywDbK+qDUZuT8HUvud16MMSaqXaM+VIWgAKEEkzD/xvRdqjKcB7PTG3HpBqRqifMFgiYue6ZyXqYvNzPbqeAf6arsRXKUFe5a8bgQthQlJiuWa3OVsfgf1w4LCvaYf/u03Lulp505shJ1jPh84+8Cgot0ZZiPRlJxJl2lTOWFsmWRqYQV+b2HBEHj0C4dGWgJmK6Sg6ngjORCqYc4LrYeiUy5b/6/em3wAlFyyMkZ+g8gtZ0TYKtKFljDFG5Y2p09B8mUYdfYM7/xdPFpwrjIQtPGnzEdIXa+a6/O+3c0PKLk4nRzLcQCWtxkoEzoSzYJyBVqMrPnHdxMxRPeQjdiLXneDkKNVcghTJy4337zUVhxmbQLf8uCeSp2knSFT6xxFTokDecfw+PF1zPeeQcqPBK5vu3uXjRXpUpsACp0hPsFN6jcqDnkl/zplpxJAyKI39vNCPv37ielf4KmVQOpoW5Omjmfacxuuk6CDwcqpjNXyGbdBoqHCv7pl9SwnzpQw7ohF9NYTGA=
    bucket: kubryant
