version: '2'

services:
  nginx:
    build:
      context: .
      dockerfile: conf/Dockerfile.dev.nginx
    links:
      - application
    ports:
      - "80:8080"

  application:
    build:
      context: .
      dockerfile: conf/Dockerfile.dev.app
    volumes:
      - .:/go/src/github.com/kubryant/kubryant.in/
