version: '2'

services:
  nginx:
    build:
      context: .
      dockerfile: conf/Dockerfile.production.nginx
    links:
      - application
    ports:
      - "443:443"
      - "80:80"

  application:
    build:
      context: .
      dockerfile: conf/Dockerfile.production.app
